export default{
    cpp:require('./assets/c++.png'),
    java:require('./assets/java.png'),
    python:require('./assets/python.png'),
    mysql:require('./assets/mysql.png'),
    web:require('./assets/web.png'),
    app:require('./assets/app.png'),
    contentWriting:require('./assets/contentwriting.png'),
    spokenEnglish:require('./assets/spokenenglish.png'),
    msoffice:require('./assets/MS_Office.png'),
    paint:require('./assets/paint.png'),
    communication:require('./assets/Communication.png'),
    html:require('./assets/html.png'),
    figma:require('./assets/Figma.png'),
    adobePremiere:require('./assets/adobepp.png'),
    adobeAfter:require('./assets/adobeae.png'),
}